name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build
        run: npm run build
        working-directory: ./frontend
      - name: Upload Build to Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/build # maybe sync build to glitch.com in the future

  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Push to Glitch
        run: echo todo automate backend deployment to glitch.com via git

  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Print Deployment URL
        run: echo "Deployment URL is ${{ steps.deployment.outputs.page_url }}"